Fix yaml/yml inconsistencies
NovatecConsulting/technologyconsulting-containerexerciseapp pull request #2
Opened 2021-10-28 06:06 UTC by xDimaa

Bitte nicht Mergen bevor dieser Pull-Request richtig aproved wurde. 

@Exzelsios @immae1 

Issue: https://jira.novatec-gmbh.de/browse/TC-524

Die Dateiendungen im wurden von "yml" auf "yaml" geändert. 
Die Inkonsistenz in den Dateien wurde ebensfalls angepasst.

2021-10-28 11:19 UTC, immae1 commented
added reviewers as @xDimaa seems not have perms here

2021-10-28 11:23 UTC, immae1 reviewed
checked changed file endings - LGTM

2021-10-29 06:09 UTC, Exzelsios approved these changes

2021-10-29 06:12 UTC, Exzelsios commented
LGTM, die anderen relevanten Changes waren ja iirc im Exercises Repo.

2021-10-29 13:29 UTC, NT-florianernst requested changes
Looking good to me, with one tiny nitpick:

In `.solutions/deployAll.sh` there are still some occurrences of `.yml`. I don't know who actually makes use of this file, but this should be adjusted nonetheless.

But apart from that great job, thanks!

The final merging should be done at @Exzelsios'es discretion, as they will next be affected by this change in a live setting.

2021-11-02 09:01 UTC, xDimaa commented
Danke @NT-florianernst für den HInweis. Ich habe noch einen Git Clone durchgeführt und nochmals die Dateien durchsucht. War ansonsten nichts mehr zu finden.

2021-11-08 11:06 UTC, NT-florianernst approved these changes

2021-12-17 14:26 UTC, merged